version: '3.1'

services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "5189:5189"
    volumes:
      - .:/app
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

      